### PR TITLE
Keycloak Operator Getting Stated

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.redhat.com/browse/KEYCLOAK-13712

YAML files might be found here: https://github.com/keycloak/keycloak-quickstarts/pull/184

### CODE REVIEW

**Comment by slaskawi** [comment]
@stianst Rebased and addressed all your comments. It works with a demo app as well.

**Comment by stianst** [comment]
I'm confused - I thought we agreed that you would follow the approach taken in the other guides and not put large amounts of YAML in the guide itself. All the YAML in the guide gives a very bad first impression and should be moved to YAML files in the QuickStarts repo.

Also, why are you creating a different adoc for the test app step when there already is one?

**Comment by slaskawi** [comment]
> I'm confused - I thought we agreed that you would follow the approach taken in the other guides and not put large amounts of YAML in the guide itself. All the YAML in the guide gives a very bad first impression and should be moved to YAML files in the QuickStarts repo.

@stianst Yes, I forgot about this. Sorry for that.

> Also, why are you creating a different adoc for the test app step when there already is one?

@stianst The `first-app.adoc` creates a Client via Admin Console and provides steps to test the whole integration. I wanted to show, how to use `KeycloakClient` CR to create a proper client and then show how to test it. This means, I had to split those two steps (creating the client and testing the app) from `first-app.adoc`.

**Comment by stianst** [comment]
The aim here is to have some short/simple/straightforward to get started with. Including all the yaml achieves the opposite

It also makes it harder to maintain (and potentially test) the guide.

This really isn't up for discussion and I want the approach to be consistent to existing guides which doesn't include large yaml snippets within the guide.

**Comment by stianst** [comment]
Let's put this on hold for a bit as you've got enough on your plate right now. Then we can have a chat about it when you get a chance.

**Comment by slaskawi** [comment]
@stianst The Getting Stated Guide has been rebased an updated. Please review it once you find a free slot.

**Pull request merged**
