### PR TITLE
Added keycloak python client to extensions

### PR DESCRIPTION
**Pull request by akhilputhiry**
Added python [keycloak client](https://github.com/akhilputhiry/keycloak-client) to extensions.

### CODE REVIEW

**Comment by akhilputhiry** [comment]
@stianst Could you please review and merge

**Comment by stianst** [comment]
Thanks - if you have time I would love a blog post around this on https://www.keycloak.org/blog.html.

**Comment by akhilputhiry** [comment]
sure @stianst will do the blog post in a day or two

**Comment by stianst** [comment]
Awesome!

**Pull request merged**
