### PR TITLE
Fix reference to keycloak.yaml to use the working one from quickstart…

### LINKED ISSUE #298: OpenShift Quickstart points to latest
### Describe the bug

When following the quickstart guide for OpenShift, the contents pertain to the 'main' branch, but the sample keycloak.yaml file shows as 'latest'. Following this guide as-is leads to errors, and modifying the parameters to match lead to a CrashLoopBackOff pod. Changing the sample yaml file to use 'main' fixes it.

### Version

17.0.1

### Expected behavior

Following the guide verbatim should succeed

### Actual behavior

Following the guide verbatim leads to errors and a possible CrashLoopBackOff in the service pod

### How to Reproduce?

Follow the guide, copy-pasting the commands directly

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DGuhr**
…s main branch

@stianst seems latest and main on quickstarts repo diverged. Not sure what is the best way to proceed here. We should align / delete "latest"?

Closes #298

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I believe guides should point to the latest released quickstarts, i.e. `latest` branch and not the `main` branch which is used for dev purposes.

**Comment by vmuzikar** [comment]
I mean, if there's some issue with YAMLs in `latest`, the fix should be done there.

**Comment by DGuhr** [comment]
@vmuzikar right, so instead of using the one from main, the root cause lies in main diverged from latest, so the changes to yaml on `main` should be added to `latest` instead. I would've done this already, but no access rights ;)

**Comment by vmuzikar** [comment]
@DGuhr As far as I can tell, the only difference is the KC image – `image: quay.io/keycloak/keycloak:18.0.0` in `latest` vs. `image: quay.io/keycloak/keycloak:nightly` in `main`.  Which is, of course, correct.

Could it be that there was some issue in 18 that was already fixed?

**Comment by DGuhr** [comment]
@vmuzikar forget about it... i had multiple wrong assumptions here. 

a) forgot about latest == release version, main == latest version (this is a bit unnecessarily complicated ^^)
b) did test that it works with the keycloak.yaml from main, but did not test if it actually works with latest, bc. believed what #298 says is true.

Long story short: I just spun up CRC and tried the quickstarts guide as is, and it works with latest, so could not reproduce. 

Closing here.

**Pull request closed without merging**
