### PR TITLE
[KEYCLOAK-8963] Broken links for Gatekeeper download

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by abstractj** [comment]
@stianst I cannot assign any reviewers for keycloak-web repo. So, I'm pinging you here :)

**Comment by stianst** [comment]
Was supposed to be compressed right, so looks like the upload was wrong rather than the link?

**Comment by abstractj** [comment]
@stianst I don't think the upload was wrong. Just try for example https://downloads.jboss.org/keycloak/4.6.0.Final/gatekeeper/keycloak-gatekeeper-linux-amd64.tar.gz.

There's something duplicating the file extension for Gatekeeper downloads, that's my guess.

**Comment by stianst** [comment]
You're right. Forgot how it works. The tar.gz and zip is added automatically.

**Comment by stianst** [comment]
Merged. It takes a while for it to propagate to keycloak.org btw. Sometimes several hours. Think it has to do with GitHub cdns

**Pull request merged**
