### PR TITLE
add missing clone command

### PR DESCRIPTION
**Pull request by magor**

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
The examples actually uses the templates directly from `https` and not from the cloned repository. So, either we should just remove the `clone repo` section completely, or the examples should use the files from the clone instead of `https`.

@pedroigor wdyt?

**Comment by pedroigor** [comment]
I think we should remove the text related to cloning the repo.

@magor Does it make sense for you?

**Comment by FullofQuarks** [comment]
If it's decided to keep the clone command (and subsequently using the cloned repo), then the typo should also be fixed:
> First step is to retrieve these files by **cloing** the repository

**Comment by pedroigor** [comment]
@magor Let's then remove `First step is to retrieve these files by cloing the repository:`.

**Comment by stianst** [comment]
Removed the mention of clo(n)ing the repo here:
https://github.com/keycloak/keycloak-web/pull/347

**Pull request closed without merging**
