### PR TITLE
Add keycloak-cluster-setup blog.

### PR DESCRIPTION
**Pull request by liqiang-fit2cloud**
Reopen https://github.com/keycloak/keycloak-web/pull/58

Modified:
1. Convert the full content of README to the blog.
2. Use the latest Keycloak version.

### CODE REVIEW

**Comment by liqiang-fit2cloud** [comment]
The blog looks like below.
snapshot

**Comment by stianst** [comment]
@liqiang-fit2cloud thanks - will ask @slaskawi to review the contents before merging

**Comment by liqiang-fit2cloud** [comment]
@sebastienblanc Would like your comment for this, thanks.

**Comment by stianst** [comment]
Thanks @liqiang-fit2cloud - I will merge this on Wednesday since we've already had a blog post today and try to spread things out a bit.

**Comment by liqiang-fit2cloud** [comment]
@stianst Got it, thanks.

**Pull request merged**
