### PR TITLE
JDBC_PING blog post

### PR DESCRIPTION
**Pull request by slaskawi**
This is a short follow-up blog post on the clustering features we introduced in our container image.

### CODE REVIEW

**Comment by slaskawi** [comment]
@stianst @hmlnarik @sebastienblanc @andymunro Please take a look once you have a chance.

**Comment by andymunro** [comment]
that can "simply" the setup.... should be that can "simplify" the setup.

**Comment by slaskawi** [comment]
> that can "simply" the setup.... should be that can "simplify" the setup.

@andymunro Fixed. Thanks for spotting this one.

**Comment by slaskawi** [comment]
@andymunro @sebastienblanc Hey guys! Could you please take a look at this one?

**Comment by slaskawi** [comment]
@sebastienblanc @andymunro So what are the further steps?

**Comment by sebastienblanc** [comment]
@slaskawi Maybe update the publication date and then we can merge (but looks like I don't have merge rights here)

**Comment by slaskawi** [comment]
Thank you @stianst

**Pull request merged**
