### PR TITLE
Update the Coordinated Vulnerability Disclosure and the security charter

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
There's two copies of security charter (security-charter and security/charter).

If you want to move security.html to security/index.html it looks like keycloak.org/security will redirect to keycloak.org/security/. However, that doesn't work in local builds as links there will just try security.html and not find it, so that would need updating. Also, the redirect is fine, but links within the website needs to be updated so it links to '/security/' instead of '/security' which causes an unessecarry redirect.

**Comment by abstractj** [comment]
@stianst thanks for pointing that out, I missed it during the changes. It's updated now. The original goal was to keep everything under the same context, like https://keycloak.org/security and https://keycloak.org/security/charter for the Security Charter. But from what I noticed, that's not possible, so I've updated those changes so that we can have https://keycloak.org/security/policy.html and https://keycloak.org/security/charter.html.

I followed the README instructions to test locally, but ran into some issues. I ended up using `python3 -m http.server --bind 127.0.0.1 8000`. Below is the expected outcome:

[Screencast from 2024-10-11 08-23-02.webm](https://github.com/user-attachments/assets/b2f6d875-720a-4633-957c-d22e65a97bdc)

**Review by stianst — COMMENTED** [review]
You are changing the link `https://www.keycloak.org/security` to `https://www.keycloak.org/security/policy` without updating any references to it. Additionally, moving it will break external links to this page.

I would just leave https://www.keycloak.org/security where it is (`pages/security.ftl`), and just use `pages/security-charter.ftl` without any sub-directories.

**Comment by abstractj** [comment]
@stianst updated to what you suggested.

**Comment by abstractj** [comment]
@jonkoops if possible, could you please review?

**Pull request merged**
